[ERROR] There is a conflict between multiple exceptions for assigning the same variable.

This justification is true:
  --> test_scope/bad/bad_sub_sub_scope.catala_en
   | 
25 |   definition y under condition a2.x + 1 = 2 consequence equals 1
   |                                ^^^^^^^^^^^^
   + Article

This justification is true:
  --> test_scope/bad/bad_sub_sub_scope.catala_en
   | 
24 |   definition y under condition a2.x = 1 consequence equals 1
   |                                ^^^^^^^^
   + Article
